Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -86,12 +86,16 @@ jobs:
           #find ./app/build/outputs/apk -type f -name "*.apk" 2>/dev/null || echo "Không có thư mục build"
 
           echo "Validating APKs"
-          for abi in arm64-v8a; do
-            if ! test -f "$APK_DIR_PATH/${APK_BASENAME_PREFIX}_$abi.apk"; then
-              files_found="$(ls "$APK_DIR_PATH")"
-              exit_on_error "Missing APK: $abi"$'\n'"$files_found"
-            fi
-          done
+
+          APK_FILE=$(find "$APK_DIR_PATH" -name "*arm64-v8a.apk" | head -n 1)
+          
+          if [ -z "$APK_FILE" ]; then
+            echo "❌ Missing APK arm64-v8a"
+            ls -R "$APK_DIR_PATH"
+            exit 1
+          fi
+          
+          echo "✅ Found APK: $APK_FILE"
 
           echo "Generating sha256sums file"
           if ! (cd "$APK_DIR_PATH"; sha256sum \
